# Generated by Django 5.2.7 on 2025-10-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_genre_publisher_alter_author_bio_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
    ]
